### PR TITLE
Numeric types include decimal Type

### PR DESCRIPTION
**Pull request by ChrisRichner**
Without this code change decimal Properties are ignored

### CODE REVIEW

**Comment by VictorioBerra** [comment]
I do not think a decimal is a supported swagger numeric type.

https://swagger.io/docs/specification/data-models/data-types/#numbers

**Comment by petriashev** [comment]
I will update samples and provide new package soon

**Comment by petriashev** [comment]
Swachbuckle Shema Minimum and Maximum has double type so it can be some fraction lose

**Comment by ChrisRichner** [comment]
Thanks, over and out 👍

**Pull request merged**
