### PR TITLE
Fixed NullReferenceException, if schema.Properties is null

### PR DESCRIPTION
**Pull request by bergmania**
I have a project, where the some schema's have Properties == null. This pull request fixes the issue :)

### CODE REVIEW

**Comment by petriashev** [comment]
Can you provide a sample?

**Comment by bergmania** [comment]
I cant provide all the code, but where you have a screenshot while debugging. Maybe you can see someting from this.

image

**Comment by petriashev** [comment]
I just wanted to reproduce this case

**Comment by petriashev** [comment]
I will accept you fix tonight

**Comment by bergmania** [comment]
Thanks :)

**Pull request merged**
